name: bee
version: 0.0.3
authors:
- Allan Berger <allan@blossom.io>
- Nik Graf <nik@blossom.io>
- Patrick Wied <patrick@blossom.io>
- Thomas Schranz <thomas@blossom.io>
description: A Collection of lightweight Dart Polymer Web Components
homepage: https://www.blossom.io/bee
dependencies:
  escape_handler: '>=0.0.2 <0.1.0'
  polymer: '>=0.11.0 <0.12.0'
transformers:
- polymer:
   entry_points:
     - example/button/index.html
     - example/secret/index.html
     - example/loading/index.html
     - example/popover/index.html
     - example/tooltip/index.html
     - example/hover-tooltip/index.html
     - example/textarea/index.html
