name: bee
authors:
- Allan Berger <allan@blossom.io>
- Nik Graf <nik@blossom.io>
- Thomas Schranz <thomas@blossom.io>
version: 0.0.2
homepage: https://www.blossom.io/bee
description: A Collection of lightweight Dart Web UI Components
dependencies:
  escape_handler: '>=0.0.2 <0.1.0'
  web_ui: '>=0.4.28 <0.5.0'
